//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AdministracionClinicaBDContext : DbContext
    {
        public AdministracionClinicaBDContext()
            : base("name=AdministracionClinicaBDContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CitasPacientes> CitasPacientes { get; set; }
        public virtual DbSet<EstadosCitas> EstadosCitas { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<TiposCitas> TiposCitas { get; set; }
    }
}
