//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    
    public partial class CitasPacientes
    {
        public int Id { get; set; }
        public int IdPaciente { get; set; }
        public int IdTipoCita { get; set; }
        public int IdEstadoCita { get; set; }
        public DateTime FechaCita { get; set; }
    
        public virtual EstadosCitas EstadosCitas { get; set; }
        public virtual Pacientes Pacientes { get; set; }
        public virtual TiposCitas TiposCitas { get; set; }
    }
}
